<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="description" content="A practical guide to drawdown depth, underwater curves, episode duration, recovery conventions, and censored unrecovered periods.">

<title>Drawdown, Underwater Duration, and Recovery – SlackQuant Research</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-5dffd768d4ee63ad8c6e2a0d3fb079ba.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-6GE45R8S4F"></script>

<script type="text/javascript">

window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-6GE45R8S4F', { 'anonymize_ip': true});
</script>
<style>html{ scroll-behavior: smooth; }</style>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="quarto-light">

<div id="quarto-search-results"></div>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#the-question" id="toc-the-question" class="nav-link active" data-scroll-target="#the-question">The Question</a></li>
  <li><a href="#start-with-the-wealth-path" id="toc-start-with-the-wealth-path" class="nav-link" data-scroll-target="#start-with-the-wealth-path">Start with the Wealth Path</a></li>
  <li><a href="#different-drawdown-percentages-use-different-denominators" id="toc-different-drawdown-percentages-use-different-denominators" class="nav-link" data-scroll-target="#different-drawdown-percentages-use-different-denominators">Different Drawdown Percentages Use Different Denominators</a></li>
  <li><a href="#maximum-drawdown-is-a-path-statistic" id="toc-maximum-drawdown-is-a-path-statistic" class="nav-link" data-scroll-target="#maximum-drawdown-is-a-path-statistic">Maximum Drawdown Is a Path Statistic</a></li>
  <li><a href="#time-under-water-needs-more-than-one-number" id="toc-time-under-water-needs-more-than-one-number" class="nav-link" data-scroll-target="#time-under-water-needs-more-than-one-number">Time Under Water Needs More Than One Number</a></li>
  <li><a href="#a-completed-drawdown-episode" id="toc-a-completed-drawdown-episode" class="nav-link" data-scroll-target="#a-completed-drawdown-episode">A Completed Drawdown Episode</a></li>
  <li><a href="#unrecovered-episodes-are-censored" id="toc-unrecovered-episodes-are-censored" class="nav-link" data-scroll-target="#unrecovered-episodes-are-censored">Unrecovered Episodes Are Censored</a></li>
  <li><a href="#why-a-20-loss-needs-a-25-gain-to-recover" id="toc-why-a-20-loss-needs-a-25-gain-to-recover" class="nav-link" data-scroll-target="#why-a-20-loss-needs-a-25-gain-to-recover">Why a 20% Loss Needs a 25% Gain to Recover</a></li>
  <li><a href="#implementation-pattern" id="toc-implementation-pattern" class="nav-link" data-scroll-target="#implementation-pattern">Implementation Pattern</a></li>
  <li><a href="#worked-path-drawdown-and-recovery-states" id="toc-worked-path-drawdown-and-recovery-states" class="nav-link" data-scroll-target="#worked-path-drawdown-and-recovery-states">Worked Path: Drawdown and Recovery States</a></li>
  <li><a href="#hands-on-lab-recompute-the-episodes" id="toc-hands-on-lab-recompute-the-episodes" class="nav-link" data-scroll-target="#hands-on-lab-recompute-the-episodes">Hands-on Lab: Recompute the Episodes</a></li>
  <li><a href="#what-a-drawdown-report-should-state" id="toc-what-a-drawdown-report-should-state" class="nav-link" data-scroll-target="#what-a-drawdown-report-should-state">What a Drawdown Report Should State</a></li>
  <li><a href="#common-mistakes" id="toc-common-mistakes" class="nav-link" data-scroll-target="#common-mistakes">Common Mistakes</a>
  <ul class="collapse">
  <li><a href="#calling-the-worst-one-period-return-maximum-drawdown" id="toc-calling-the-worst-one-period-return-maximum-drawdown" class="nav-link" data-scroll-target="#calling-the-worst-one-period-return-maximum-drawdown">1. Calling the worst one-period return “maximum drawdown”</a></li>
  <li><a href="#switching-denominators-without-changing-the-label" id="toc-switching-denominators-without-changing-the-label" class="nav-link" data-scroll-target="#switching-denominators-without-changing-the-label">2. Switching denominators without changing the label</a></li>
  <li><a href="#mixing-positive-drawdown-depth-with-a-negative-underwater-chart" id="toc-mixing-positive-drawdown-depth-with-a-negative-underwater-chart" class="nav-link" data-scroll-target="#mixing-positive-drawdown-depth-with-a-negative-underwater-chart">3. Mixing positive drawdown depth with a negative underwater chart</a></li>
  <li><a href="#treating-below-peak-observations-as-peak-to-recovery-duration" id="toc-treating-below-peak-observations-as-peak-to-recovery-duration" class="nav-link" data-scroll-target="#treating-below-peak-observations-as-peak-to-recovery-duration">4. Treating below-peak observations as peak-to-recovery duration</a></li>
  <li><a href="#fabricating-recovery-at-the-sample-end" id="toc-fabricating-recovery-at-the-sample-end" class="nav-link" data-scroll-target="#fabricating-recovery-at-the-sample-end">5. Fabricating recovery at the sample end</a></li>
  <li><a href="#requiring-a-strict-new-high-when-recovery-is-defined-at-the-prior-peak" id="toc-requiring-a-strict-new-high-when-recovery-is-defined-at-the-prior-peak" class="nav-link" data-scroll-target="#requiring-a-strict-new-high-when-recovery-is-defined-at-the-prior-peak">6. Requiring a strict new high when recovery is defined at the prior peak</a></li>
  <li><a href="#ignoring-sampling-frequency" id="toc-ignoring-sampling-frequency" class="nav-link" data-scroll-target="#ignoring-sampling-frequency">7. Ignoring sampling frequency</a></li>
  <li><a href="#reading-depth-as-a-forecast-of-recovery-time" id="toc-reading-depth-as-a-forecast-of-recovery-time" class="nav-link" data-scroll-target="#reading-depth-as-a-forecast-of-recovery-time">8. Reading depth as a forecast of recovery time</a></li>
  </ul></li>
  <li><a href="#when-this-setup-needs-to-be-extended" id="toc-when-this-setup-needs-to-be-extended" class="nav-link" data-scroll-target="#when-this-setup-needs-to-be-extended">When This Setup Needs to Be Extended</a></li>
  <li><a href="#related-methods" id="toc-related-methods" class="nav-link" data-scroll-target="#related-methods">Related Methods</a></li>
  <li><a href="#used-in-slackquant-research" id="toc-used-in-slackquant-research" class="nav-link" data-scroll-target="#used-in-slackquant-research">Used in SlackQuant Research</a></li>
  <li><a href="#reproducibility" id="toc-reproducibility" class="nav-link" data-scroll-target="#reproducibility">Reproducibility</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">
<header class="sq-platform-header">
  <div class="sq-platform-shell sq-platform-nav">
    <a class="sq-platform-brand" href="https://research.slackquant.com/" target="_self">SlackQuant Research</a>
    <nav class="sq-platform-nav-links" aria-label="Primary">
      <a href="https://research.slackquant.com/research/" target="_self">Research</a>
      <a href="https://research.slackquant.com/methods/" target="_self">Methods</a>
      <a href="https://research.slackquant.com/about/" target="_self">About</a>
      <a class="sq-platform-ext" href="https://github.com/slackquant80/slackquant-research" target="_blank" rel="noopener noreferrer">GitHub</a>
    </nav>
  </div>
</header>
<script id="sq-header-relocator">
  (() => {
    const script = document.currentScript;
    const header = script?.previousElementSibling;
    const quartoContent = document.getElementById("quarto-content");
    if (
      header?.classList.contains("sq-platform-header") &&
      quartoContent?.parentNode
    ) {
      quartoContent.parentNode.insertBefore(header, quartoContent);
    }
  })();
</script>

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Drawdown, Underwater Duration, and Recovery</h1>
<p class="subtitle lead">Measuring how far a portfolio falls, how long it remains below its peak, and what counts as recovery</p>
  <div class="quarto-categories">
    <div class="quarto-category">Investment Methods</div>
    <div class="quarto-category">Portfolio Methods</div>
    <div class="quarto-category">Foundation</div>
  </div>
  </div>

<div>
  <div class="description">
    A practical guide to drawdown depth, underwater curves, episode duration, recovery conventions, and censored unrecovered periods.
  </div>
</div>


<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="method-kicker">
<p>QM008 · Investment Methods · Portfolio Methods · Foundation</p>
</div>
<div class="method-orientation">
<p><strong>Core idea.</strong> Drawdown measures how far current wealth is below a running high-water mark. Duration adds a second question: how long has the portfolio remained below that peak, and has recovery actually been observed?</p>
<p><strong>Use it for.</strong> Describing historical path risk, comparing the depth and persistence of losses, and reporting recovery episodes with explicit conventions.</p>
<p><strong>It does not establish.</strong> How quickly a future drawdown will recover, whether a strategy is attractive, or whether one historical maximum drawdown is a stable population risk parameter. Measurement is descriptive; prediction and portfolio optimization are separate problems.</p>
</div>
<section id="the-question" class="level1">
<h1>The Question</h1>
<p>A portfolio can finish a year with a modest return and still have experienced substantial interim losses. A one-period loss does not tell us whether wealth is just below a recent high, 20% below a peak reached months ago, or still underwater after a long incomplete recovery.</p>
<p>Drawdown measurement therefore needs three elements:</p>
<ol type="1">
<li><strong>depth</strong> — how far wealth is below its running high-water mark;</li>
<li><strong>time</strong> — how long the current or completed underwater episode lasts; and</li>
<li><strong>recovery</strong> — the exact rule used to decide that the old peak has been regained.</li>
</ol>
<p>Although the formulas are simple, the reported values depend on several conventions. Different denominators, sign conventions, recovery inequalities, duration counts, observation frequencies, and cash-flow treatments can produce different numbers from the same economic path.</p>
</section>
<section id="start-with-the-wealth-path" class="level1">
<h1>Start with the Wealth Path</h1>
<p>Let <span class="math inline">\(W_t&gt;0\)</span> be portfolio wealth or NAV at observation <span class="math inline">\(t\)</span> on a regular discrete-time grid. Define the running high-water mark</p>
<p><span class="math display">\[
H_t = \max_{0\le s\le t} W_s.
\]</span></p>
<p>QM008 uses the <strong>peak-normalized relative drawdown</strong> convention</p>
<p><span class="math display">\[
d_t
=
\frac{H_t-W_t}{H_t}
=
1-\frac{W_t}{H_t},
\qquad 0\le d_t&lt;1.
\]</span></p>
<p>This convention measures the percentage loss relative to the historical peak. Chen et al.&nbsp;use this high-water-mark normalization in their treatment of relative drawdown <span class="citation" data-cites="chenetal2015">(<a href="#ref-chenetal2015" role="doc-biblioref">Chen et al. 2015</a>)</span>.</p>
<p>The same state can be plotted as a signed <strong>underwater series</strong></p>
<p><span class="math display">\[
u_t
=
\frac{W_t}{H_t}-1
=
-d_t,
\]</span></p>
<p>so <span class="math inline">\(u_t\le0\)</span>. A 20% drawdown is therefore either <span class="math inline">\(d_t=0.20\)</span> or <span class="math inline">\(u_t=-0.20\)</span>, depending on whether the chart displays positive loss depth or a negative underwater return. The sign convention should be stated rather than inferred from the picture.</p>
<div id="fig-qm008-wealth" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Wealth path and running high-water mark showing one completed drawdown and one unrecovered final episode.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-qm008-wealth-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/rendered/qm008_wealth_highwater.svg" class="img-fluid figure-img" style="width:94.0%" alt="Wealth path and running high-water mark showing one completed drawdown and one unrecovered final episode.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-qm008-wealth-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: The wealth path is evaluated against its running high-water mark. The first episode peaks at 110, falls to 88, and recovers exactly to 110; the final episode remains unrecovered at the sample end.
</figcaption>
</figure>
</div>
</section>
<section id="different-drawdown-percentages-use-different-denominators" class="level1">
<h1>Different Drawdown Percentages Use Different Denominators</h1>
<p>The literature uses several related drawdown measures that are not numerically interchangeable. Absolute drawdown is the distance <span class="math inline">\(H_t-W_t\)</span> <span class="citation" data-cites="carrzhanghadjiliadis2011 goldbergmahmoud2017">(<a href="#ref-carrzhanghadjiliadis2011" role="doc-biblioref">Carr et al. 2011</a>; <a href="#ref-goldbergmahmoud2017" role="doc-biblioref">Goldberg and Mahmoud 2017</a>)</span>. The percentage convention used here divides that loss by the peak <span class="math inline">\(H_t\)</span>. Chekhlov, Uryasev, and Zabarankin illustrate why the denominator must be named explicitly: their introductory wealth-drop expression uses current wealth in the denominator <span class="citation" data-cites="chekhlovuryasevzabarankin2005">(<a href="#ref-chekhlovuryasevzabarankin2005" role="doc-biblioref">Chekhlov et al. 2005</a>)</span>.</p>
<p>Take a peak of 110 and current wealth of 88:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Quantity</th>
<th style="text-align: center;">Formula</th>
<th style="text-align: center;">Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Absolute drawdown</td>
<td style="text-align: center;"><span class="math inline">\(H-W\)</span></td>
<td style="text-align: center;">22</td>
</tr>
<tr class="even">
<td>Peak-normalized drawdown — QM008</td>
<td style="text-align: center;"><span class="math inline">\((H-W)/H\)</span></td>
<td style="text-align: center;">20.000%</td>
</tr>
<tr class="odd">
<td>Current-value-normalized drop</td>
<td style="text-align: center;"><span class="math inline">\((H-W)/W\)</span></td>
<td style="text-align: center;">25.000%</td>
</tr>
<tr class="even">
<td>Log drawdown</td>
<td style="text-align: center;"><span class="math inline">\(\log(H/W)\)</span></td>
<td style="text-align: center;">0.22314</td>
</tr>
</tbody>
</table>
<p>For positive wealth, the log version satisfies</p>
<p><span class="math display">\[
\log\frac{H_t}{W_t}
=
-\log(1-d_t),
\]</span></p>
<p>so it is not generally equal to <span class="math inline">\(d_t\)</span>.</p>
<div class="callout callout-style-default callout-important callout-titled" title="State the denominator and sign">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>State the denominator and sign
</div>
</div>
<div class="callout-body-container callout-body">
<p>A label such as “maximum drawdown = 20%” is incomplete if the calculation convention is not clear. QM008 uses positive, peak-normalized drawdown depth <span class="math inline">\(d_t=(H_t-W_t)/H_t\)</span> and uses <span class="math inline">\(u_t=-d_t\)</span> only when referring to the signed underwater curve.</p>
</div>
</div>
</section>
<section id="maximum-drawdown-is-a-path-statistic" class="level1">
<h1>Maximum Drawdown Is a Path Statistic</h1>
<p>Over observations <span class="math inline">\(0,\ldots,T\)</span>, define</p>
<p><span class="math display">\[
\operatorname{MDD}_{0:T}
=
\max_{0\le t\le T} d_t.
\]</span></p>
<p>In the deterministic path used here,</p>
<p><span class="math display">\[
W=(100,110,99,88,99,110,121,115,121,122,100),
\]</span></p>
<p>maximum drawdown is 20%, reached when wealth falls from the high-water mark 110 to 88.</p>
<div id="fig-qm008-underwater" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Signed underwater series showing zero at high-water marks and negative values during drawdown episodes.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-qm008-underwater-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/rendered/qm008_underwater.svg" class="img-fluid figure-img" style="width:92.0%" alt="Signed underwater series showing zero at high-water marks and negative values during drawdown episodes.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-qm008-underwater-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: The signed underwater series is zero at each high-water mark and negative while wealth is below the relevant peak. The final observation is still underwater, so its recovery duration is not yet observed.
</figcaption>
</figure>
</div>
<p>Maximum drawdown is not a one-period return statistic. It is generated by the compounded path and its running maximum. It is also sample-dependent. Goldberg and Mahmoud emphasize that drawdown measures depend on the observation horizon and can be sensitive to sampling frequency <span class="citation" data-cites="goldbergmahmoud2017">(<a href="#ref-goldbergmahmoud2017" role="doc-biblioref">Goldberg and Mahmoud 2017</a>)</span>. A monthly series can miss an intramonth trough that would appear in daily data.</p>
</section>
<section id="time-under-water-needs-more-than-one-number" class="level1">
<h1>Time Under Water Needs More Than One Number</h1>
<p>Depth and time answer different questions. A shallow drawdown can persist for a long time; a deep drawdown can recover quickly. The literature treats drawdown duration as a distinct object, often associated with “time to recover” the historical maximum <span class="citation" data-cites="landriaultlizhang2017">(<a href="#ref-landriaultlizhang2017" role="doc-biblioref">Landriault et al. 2017</a>)</span>. Proietti likewise models elapsed time since the most recent peak as its own state process rather than as drawdown magnitude <span class="citation" data-cites="proietti2026">(<a href="#ref-proietti2026" role="doc-biblioref">Proietti 2026</a>)</span>.</p>
<p>For clarity, distinguish <strong>current underwater age</strong> from a <strong>completed episode duration</strong>.</p>
<p>For an observation with <span class="math inline">\(d_t&gt;0\)</span>, let</p>
<p><span class="math display">\[
p_t
=
\max\{s\le t: W_s=H_t\}
\]</span></p>
<p>be the most recent time the current high-water mark was actually attained. On the regular grid, current underwater age is</p>
<p><span class="math display">\[
a_t=t-p_t,
\]</span></p>
<p>and <span class="math inline">\(a_t=0\)</span> whenever <span class="math inline">\(d_t=0\)</span>.</p>
<p>This point-in-time state grows while the portfolio remains underwater and resets to zero when the old peak is regained.</p>
</section>
<section id="a-completed-drawdown-episode" class="level1">
<h1>A Completed Drawdown Episode</h1>
<p>Consider a drawdown episode that begins at peak index <span class="math inline">\(p\)</span>. Under the QM008 convention, recovery occurs at the first later observation</p>
<p><span class="math display">\[
q
=
\min\{t&gt;p:W_t\ge W_p\}.
\]</span></p>
<p><strong>Equality counts as recovery.</strong> The portfolio does not need to make a strict new all-time high. A strict-new-high condition, <span class="math inline">\(W_q &gt; W_p\)</span>, is a different convention and can produce a later recovery date.</p>
<p>Within a completed episode, let <span class="math inline">\(m\)</span> be an index attaining the minimum wealth after the peak and before recovery. If the trough is tied, the example code records the <strong>earliest</strong> minimum. The elapsed times are then reported explicitly:</p>
<p><span class="math display">\[
\text{time to trough}=m-p,
\]</span></p>
<p><span class="math display">\[
\text{trough-to-recovery time}=q-m,
\]</span></p>
<p>and</p>
<p><span class="math display">\[
\text{peak-to-recovery duration}=q-p.
\]</span></p>
<p>For the first episode in the example:</p>
<ul>
<li>peak: <span class="math inline">\(p=1\)</span>, <span class="math inline">\(W_p=110\)</span>;</li>
<li>trough: <span class="math inline">\(m=3\)</span>, <span class="math inline">\(W_m=88\)</span>;</li>
<li>recovery: <span class="math inline">\(q=5\)</span>, <span class="math inline">\(W_q=110\)</span>;</li>
<li>maximum episode depth: 20%;</li>
<li>time to trough: 2 intervals;</li>
<li>trough-to-recovery: 2 intervals;</li>
<li>peak-to-recovery duration: 4 intervals.</li>
</ul>
<p>There are only <strong>three observations strictly below 110</strong>: <span class="math inline">\(t=2,3,4\)</span>. That count is not the same thing as the four elapsed intervals from peak to recovery.</p>
<div class="callout callout-style-default callout-warning callout-titled" title="Specify what duration counts">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>Specify what duration counts
</div>
</div>
<div class="callout-body-container callout-body">
<p>“Underwater for three observations” and “four intervals from peak to recovery” can both describe the same episode. State which quantity you are reporting. On irregular timestamps, an index difference is not automatically a calendar duration.</p>
</div>
</div>
</section>
<section id="unrecovered-episodes-are-censored" class="level1">
<h1>Unrecovered Episodes Are Censored</h1>
<p>The final example episode begins at <span class="math inline">\(t=9\)</span> with wealth 122 and ends the sample at <span class="math inline">\(t=10\)</span> with wealth 100. The drawdown-to-date is</p>
<p><span class="math display">\[
1-\frac{100}{122}
\approx 18.03\%.
\]</span></p>
<p>But no recovery has been observed. The completed peak-to-recovery duration is therefore <strong>unknown</strong>. It should not be replaced by either one interval or the elapsed time from the peak to the sample end.</p>
<p>QM008 records such an episode as <strong>right-censored</strong>. It can report the peak, trough-to-date, depth-to-date, and age-to-date, while leaving completed recovery duration missing.</p>
<p>This distinction matters whenever drawdown histories are summarized statistically. Treating the sample end as a recovery date converts an incomplete episode into a completed observation.</p>
</section>
<section id="why-a-20-loss-needs-a-25-gain-to-recover" class="level1">
<h1>Why a 20% Loss Needs a 25% Gain to Recover</h1>
<p>Drawdown percentages are asymmetric around the peak. If wealth falls by a peak-normalized fraction <span class="math inline">\(d\)</span> from <span class="math inline">\(H\)</span> to <span class="math inline">\(H(1-d)\)</span>, the trough-to-peak gain required to recover is</p>
<p><span class="math display">\[
g_{\text{recover}}
=
\frac{H}{H(1-d)}-1
=
\frac{d}{1-d}.
\]</span></p>
<p>For <span class="math inline">\(d=0.20\)</span>,</p>
<p><span class="math display">\[
g_{\text{recover}}=\frac{0.20}{0.80}=0.25.
\]</span></p>
<p>This is an algebraic identity. It says <strong>how large</strong> the required gain is, not <strong>how long</strong> recovery will take. QM008 makes no forecast of future recovery speed.</p>
</section>
<section id="implementation-pattern" class="level1">
<h1>Implementation Pattern</h1>
<p>A transparent discrete-time implementation keeps the high-water mark and episode state explicit:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>high <span class="op">=</span> wealth[<span class="dv">0</span>]</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>peak_index <span class="op">=</span> <span class="dv">0</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> t, value <span class="kw">in</span> <span class="bu">enumerate</span>(wealth):</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> value <span class="op">&gt;=</span> high:</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>        high <span class="op">=</span> value</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>        peak_index <span class="op">=</span> t</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>        drawdown <span class="op">=</span> <span class="fl">0.0</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>        underwater_age <span class="op">=</span> <span class="dv">0</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>    <span class="cf">else</span>:</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>        drawdown <span class="op">=</span> <span class="fl">1.0</span> <span class="op">-</span> value <span class="op">/</span> high</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>        underwater_age <span class="op">=</span> t <span class="op">-</span> peak_index</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>To identify episodes, the implementation also records the recovery condition, trough-selection rule, and censoring status. The accompanying code returns both the point-in-time drawdown state and a table of completed and censored episodes.</p>
</section>
<section id="worked-path-drawdown-and-recovery-states" class="level1">
<h1>Worked Path: Drawdown and Recovery States</h1>
<p>The example path is small enough to inspect by hand:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 17%">
<col style="width: 17%">
<col style="width: 17%">
<col style="width: 17%">
<col style="width: 17%">
<col style="width: 10%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;"><span class="math inline">\(t\)</span></th>
<th style="text-align: center;">Wealth <span class="math inline">\(W_t\)</span></th>
<th style="text-align: center;">HWM <span class="math inline">\(H_t\)</span></th>
<th style="text-align: center;">Drawdown <span class="math inline">\(d_t\)</span></th>
<th style="text-align: center;">Underwater age <span class="math inline">\(a_t\)</span></th>
<th>State</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">0</td>
<td style="text-align: center;">100</td>
<td style="text-align: center;">100</td>
<td style="text-align: center;">0.000%</td>
<td style="text-align: center;">0</td>
<td>high-water mark</td>
</tr>
<tr class="even">
<td style="text-align: center;">1</td>
<td style="text-align: center;">110</td>
<td style="text-align: center;">110</td>
<td style="text-align: center;">0.000%</td>
<td style="text-align: center;">0</td>
<td>new peak</td>
</tr>
<tr class="odd">
<td style="text-align: center;">2</td>
<td style="text-align: center;">99</td>
<td style="text-align: center;">110</td>
<td style="text-align: center;">10.000%</td>
<td style="text-align: center;">1</td>
<td>underwater</td>
</tr>
<tr class="even">
<td style="text-align: center;">3</td>
<td style="text-align: center;">88</td>
<td style="text-align: center;">110</td>
<td style="text-align: center;">20.000%</td>
<td style="text-align: center;">2</td>
<td>trough</td>
</tr>
<tr class="odd">
<td style="text-align: center;">4</td>
<td style="text-align: center;">99</td>
<td style="text-align: center;">110</td>
<td style="text-align: center;">10.000%</td>
<td style="text-align: center;">3</td>
<td>underwater</td>
</tr>
<tr class="even">
<td style="text-align: center;">5</td>
<td style="text-align: center;">110</td>
<td style="text-align: center;">110</td>
<td style="text-align: center;">0.000%</td>
<td style="text-align: center;">0</td>
<td>equality recovery</td>
</tr>
<tr class="odd">
<td style="text-align: center;">6</td>
<td style="text-align: center;">121</td>
<td style="text-align: center;">121</td>
<td style="text-align: center;">0.000%</td>
<td style="text-align: center;">0</td>
<td>new peak</td>
</tr>
<tr class="even">
<td style="text-align: center;">7</td>
<td style="text-align: center;">115</td>
<td style="text-align: center;">121</td>
<td style="text-align: center;">4.959%</td>
<td style="text-align: center;">1</td>
<td>underwater</td>
</tr>
<tr class="odd">
<td style="text-align: center;">8</td>
<td style="text-align: center;">121</td>
<td style="text-align: center;">121</td>
<td style="text-align: center;">0.000%</td>
<td style="text-align: center;">0</td>
<td>equality recovery</td>
</tr>
<tr class="even">
<td style="text-align: center;">9</td>
<td style="text-align: center;">122</td>
<td style="text-align: center;">122</td>
<td style="text-align: center;">0.000%</td>
<td style="text-align: center;">0</td>
<td>new peak</td>
</tr>
<tr class="odd">
<td style="text-align: center;">10</td>
<td style="text-align: center;">100</td>
<td style="text-align: center;">122</td>
<td style="text-align: center;">18.033%</td>
<td style="text-align: center;">1</td>
<td>underwater; censored</td>
</tr>
</tbody>
</table>
<div class="callout callout-style-default callout-note callout-titled" title="Illustrative path — not empirical evidence">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Illustrative path — not empirical evidence
</div>
</div>
<div class="callout-body-container callout-body">
<p>The numbers are chosen to illustrate definition and indexing issues, including exact equality recovery and a censored final episode. They do not describe the frequency or severity of real-world drawdowns.</p>
</div>
</div>
</section>
<section id="hands-on-lab-recompute-the-episodes" class="level1">
<h1>Hands-on Lab: Recompute the Episodes</h1>
<p>The lab reads the same wealth path, computes the running high-water mark, drawdown depth, signed underwater series, underwater age, and episode table, and prints the completed versus censored recovery states.</p>
<div class="method-action">
<p><strong>Run it yourself.</strong> Start with the <a href="../../40_PORTFOLIO_METHODS/QM008_DRAWDOWN_UNDERWATER_DURATION_RECOVERY/labs/index.html">lab guide</a>. For a self-contained copy, use the <a href="labs/qm008_hands_on_lab_bundle.zip">complete lab bundle</a>. Direct source: <a href="labs/python/qm008_hands_on.py">Python</a> · <a href="labs/r/qm008_hands_on.R">R</a>.</p>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="ex">python</span> labs/python/qm008_hands_on.py</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>A useful exercise is to change the final wealth from 100 to 122. Under the same equality-recovery convention, the last episode then becomes completed instead of censored. The convention is unchanged; only the observed path changes.</p>
</section>
<section id="what-a-drawdown-report-should-state" class="level1">
<h1>What a Drawdown Report Should State</h1>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Item</th>
<th>Minimum declaration</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Wealth input</td>
<td>Price wealth, total-return wealth, NAV, or another path; strictly positive in the setup used here</td>
</tr>
<tr class="even">
<td>High-water-mark initialization</td>
<td>In-sample start or an externally supplied prior HWM</td>
</tr>
<tr class="odd">
<td>Drawdown formula</td>
<td>Absolute, peak-normalized percentage, current-value normalization, log, or another named convention</td>
</tr>
<tr class="even">
<td>Sign</td>
<td>Positive loss depth or negative underwater series</td>
</tr>
<tr class="odd">
<td>Recovery threshold</td>
<td>Regain the prior peak (<span class="math inline">\(W_q \ge W_p\)</span>) or require a strict new high (<span class="math inline">\(W_q &gt; W_p\)</span>)</td>
</tr>
<tr class="even">
<td>Duration unit</td>
<td>Elapsed grid intervals, below-peak observation count, or actual calendar time</td>
</tr>
<tr class="odd">
<td>Trough tie rule</td>
<td>Which trough is recorded when the minimum is tied</td>
</tr>
<tr class="even">
<td>Unrecovered episode</td>
<td>Right-censored or another explicitly justified treatment</td>
</tr>
<tr class="odd">
<td>Sampling</td>
<td>Daily, weekly, monthly, or another grid</td>
</tr>
<tr class="even">
<td>External cash flows</td>
<td>No-flow path or a return/NAV series adjusted so flows do not masquerade as investment performance</td>
</tr>
</tbody>
</table>
<p>Time-weighted performance standards explicitly adjust or neutralize external cash flows because client-driven flows can distort performance measurement <span class="citation" data-cites="gips2020handbook">(<a href="#ref-gips2020handbook" role="doc-biblioref">CFA Institute 2020</a>)</span>. Drawdown computed from raw account value across an unadjusted subscription or redemption can therefore describe the cash-flow path rather than the investment path.</p>
</section>
<section id="common-mistakes" class="level1">
<h1>Common Mistakes</h1>
<section id="calling-the-worst-one-period-return-maximum-drawdown" class="level2">
<h2 class="anchored" data-anchor-id="calling-the-worst-one-period-return-maximum-drawdown">1. Calling the worst one-period return “maximum drawdown”</h2>
<p>Maximum drawdown comes from the compounded wealth path relative to a running peak. A 10% monthly loss produces a 10% drawdown when the period starts at the high-water mark, but it can occur inside a materially deeper drawdown when the portfolio was already underwater.</p>
</section>
<section id="switching-denominators-without-changing-the-label" class="level2">
<h2 class="anchored" data-anchor-id="switching-denominators-without-changing-the-label">2. Switching denominators without changing the label</h2>
<p>At a peak of 110 and current wealth of 88, <span class="math inline">\((H-W)/H=20\%\)</span> while <span class="math inline">\((H-W)/W=25\%\)</span>. Both cannot be reported as the same “drawdown percentage.”</p>
</section>
<section id="mixing-positive-drawdown-depth-with-a-negative-underwater-chart" class="level2">
<h2 class="anchored" data-anchor-id="mixing-positive-drawdown-depth-with-a-negative-underwater-chart">3. Mixing positive drawdown depth with a negative underwater chart</h2>
<p>Under the QM008 convention, they are the same state with opposite sign: <span class="math inline">\(u_t=-d_t\)</span>.</p>
</section>
<section id="treating-below-peak-observations-as-peak-to-recovery-duration" class="level2">
<h2 class="anchored" data-anchor-id="treating-below-peak-observations-as-peak-to-recovery-duration">4. Treating below-peak observations as peak-to-recovery duration</h2>
<p>In the first example episode, three observations are strictly underwater but four intervals elapse from the peak to the equality recovery.</p>
</section>
<section id="fabricating-recovery-at-the-sample-end" class="level2">
<h2 class="anchored" data-anchor-id="fabricating-recovery-at-the-sample-end">5. Fabricating recovery at the sample end</h2>
<p>An unrecovered final episode is right-censored. The sample end tells us its age-to-date, not its completed recovery duration.</p>
</section>
<section id="requiring-a-strict-new-high-when-recovery-is-defined-at-the-prior-peak" class="level2">
<h2 class="anchored" data-anchor-id="requiring-a-strict-new-high-when-recovery-is-defined-at-the-prior-peak">6. Requiring a strict new high when recovery is defined at the prior peak</h2>
<p><span class="math inline">\(W_q \ge W_p\)</span> and <span class="math inline">\(W_q &gt; W_p\)</span> define different recovery rules. If the stated convention counts regaining the prior peak as recovery, a backtest or risk report should not silently replace it with a strict-new-high rule.</p>
</section>
<section id="ignoring-sampling-frequency" class="level2">
<h2 class="anchored" data-anchor-id="ignoring-sampling-frequency">7. Ignoring sampling frequency</h2>
<p>Historical MDD can change when a finer observation grid reveals an interim trough that a coarser grid misses <span class="citation" data-cites="goldbergmahmoud2017">(<a href="#ref-goldbergmahmoud2017" role="doc-biblioref">Goldberg and Mahmoud 2017</a>)</span>.</p>
</section>
<section id="reading-depth-as-a-forecast-of-recovery-time" class="level2">
<h2 class="anchored" data-anchor-id="reading-depth-as-a-forecast-of-recovery-time">8. Reading depth as a forecast of recovery time</h2>
<p>The identity <span class="math inline">\(d/(1-d)\)</span> gives the gain required to regain the old peak. It does not say how quickly or whether that gain will occur.</p>
</section>
</section>
<section id="when-this-setup-needs-to-be-extended" class="level1">
<h1>When This Setup Needs to Be Extended</h1>
<p>The formulas above are scoped to strictly positive wealth on the stated observation grid. Additional definitions or accounting are needed for:</p>
<ul>
<li>wealth paths that can be zero or negative;</li>
<li>leveraged structures in which ordinary percentage-from-peak interpretation becomes unstable;</li>
<li>irregular timestamps when calendar duration matters;</li>
<li>raw account values with unadjusted subscriptions or redemptions;</li>
<li>benchmark-relative drawdown;</li>
<li>Conditional Expected Drawdown or drawdown-constrained optimization; or</li>
<li>empirical models that forecast time to recovery.</li>
</ul>
<p>Each case requires additional definitions, evidence, or accounting beyond the setup used here.</p>
</section>
<section id="related-methods" class="level1 related-methods">
<h1 class="related-methods">Related Methods</h1>
<ul>
<li><a href="../../40_PORTFOLIO_METHODS/QM007_PORTFOLIO_BACKTESTING_REBALANCING/article.html">QM007 — Portfolio Backtesting and Rebalancing</a>: constructs the wealth path on which drawdown is measured and makes the portfolio timeline explicit.</li>
</ul>
</section>
<section id="used-in-slackquant-research" class="level1">
<h1>Used in SlackQuant Research</h1>
<p><a href="https://research.slackquant.com/research/protection-patience/"><strong>When Protection Works but the Portfolio Still Lags</strong></a> uses own-path maximum drawdown and high-water-mark logic to separate realized downside protection from benchmark-relative path burden. The definitions here cover the general drawdown, underwater-age, recovery, and censoring mechanics. The paper’s benchmark-relative strategy-to-equity wealth-ratio measure remains application-specific and is defined in the research paper rather than here.</p>
</section>
<section id="reproducibility" class="level1">
<h1>Reproducibility</h1>
<p>The accompanying materials include the illustrative wealth path, Python and base-R implementations, reproducible figures, numerical checks, and a hands-on lab. The example code independently reconstructs high-water marks, drawdown depth, underwater age, completed episodes, and the right-censored terminal episode used above.</p>
</section>
<section id="references" class="level1 unnumbered">
<h1 class="unnumbered">References</h1>
<div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-carrzhanghadjiliadis2011" class="csl-entry" role="listitem">
Carr, Peter, Hongzhong Zhang, and Olympia Hadjiliadis. 2011. <span>“Maximum Drawdown Insurance.”</span> <em>International Journal of Theoretical and Applied Finance</em> 14 (8): 1195–230. <a href="https://doi.org/10.1142/S0219024911006826">https://doi.org/10.1142/S0219024911006826</a>.
</div>
<div id="ref-gips2020handbook" class="csl-entry" role="listitem">
CFA Institute. 2020. <span>“GIPS Standards Handbook for Firms.”</span> <a href="https://www.gipsstandards.org/standards/gips-standards-for-firms/gips-standards-handbook-for-firms/">https://www.gipsstandards.org/standards/gips-standards-for-firms/gips-standards-handbook-for-firms/</a>.
</div>
<div id="ref-chekhlovuryasevzabarankin2005" class="csl-entry" role="listitem">
Chekhlov, Alexei, Stanislav Uryasev, and Michael Zabarankin. 2005. <span>“Drawdown Measure in Portfolio Optimization.”</span> <em>International Journal of Theoretical and Applied Finance</em> 8 (1): 13–58. <a href="https://doi.org/10.1142/S0219024905002767">https://doi.org/10.1142/S0219024905002767</a>.
</div>
<div id="ref-chenetal2015" class="csl-entry" role="listitem">
Chen, Xinfu, David Landriault, Bin Li, and Dongchen Li. 2015. <span>“On Minimizing Drawdown Risks of Lifetime Investments.”</span> <em>Insurance: Mathematics and Economics</em> 65: 46–54. <a href="https://doi.org/10.1016/j.insmatheco.2015.08.007">https://doi.org/10.1016/j.insmatheco.2015.08.007</a>.
</div>
<div id="ref-goldbergmahmoud2017" class="csl-entry" role="listitem">
Goldberg, Lisa R., and Ola Mahmoud. 2017. <span>“Drawdown: From Practice to Theory and Back Again.”</span> <em>Mathematics and Financial Economics</em> 11: 275–97. <a href="https://doi.org/10.1007/s11579-016-0181-9">https://doi.org/10.1007/s11579-016-0181-9</a>.
</div>
<div id="ref-landriaultlizhang2017" class="csl-entry" role="listitem">
Landriault, David, Bin Li, and Hongzhong Zhang. 2017. <span>“On Magnitude, Asymptotics and Duration of Drawdowns for Lévy Models.”</span> <em>Bernoulli</em> 23 (1): 432–58. <a href="https://doi.org/10.3150/15-BEJ748">https://doi.org/10.3150/15-BEJ748</a>.
</div>
<div id="ref-proietti2026" class="csl-entry" role="listitem">
Proietti, Tommaso. 2026. <span>“Ups and (Draw) Downs.”</span> <em>International Journal of Forecasting</em> 42 (2): 457–73. <a href="https://doi.org/10.1016/j.ijforecast.2025.07.008">https://doi.org/10.1016/j.ijforecast.2025.07.008</a>.
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/research\.slackquant\.com\/methods\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>SlackQuant Research · Quantitative Methods</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p>Methods for applied quantitative research and investment practice</p>
</div>
  </div>
</footer>
<script id="sq-method-browser-script">
  (() => {
    const methods = [
      { id: "QM001", title: "Out-of-Sample Forecast Evaluation", path: "10_FORECAST_EVALUATION/QM001_OUT_OF_SAMPLE_EVALUATION/article.html", folder: "QM001_OUT_OF_SAMPLE_EVALUATION" },
      { id: "QM002", title: "Rolling vs Expanding Windows", path: "10_FORECAST_EVALUATION/QM002_ROLLING_VS_EXPANDING_WINDOWS/article.html", folder: "QM002_ROLLING_VS_EXPANDING_WINDOWS" },
      { id: "QM003", title: "Look-Ahead Bias and Data Leakage", path: "80_DATA_RESEARCH_DESIGN/QM003_LOOK_AHEAD_BIAS_DATA_LEAKAGE/article.html", folder: "QM003_LOOK_AHEAD_BIAS_DATA_LEAKAGE" },
      { id: "QM004", title: "Diebold–Mariano Test", path: "10_FORECAST_EVALUATION/QM004_DIEBOLD_MARIANO_TEST/article.html", folder: "QM004_DIEBOLD_MARIANO_TEST" },
      { id: "QM005", title: "Model Confidence Set", path: "10_FORECAST_EVALUATION/QM005_MODEL_CONFIDENCE_SET/article.html", folder: "QM005_MODEL_CONFIDENCE_SET" },
      { id: "QM006", title: "Block Bootstrap", path: "20_STATISTICAL_INFERENCE/QM006_BLOCK_BOOTSTRAP/article.html", folder: "QM006_BLOCK_BOOTSTRAP" },
      { id: "QM007", title: "Portfolio Backtesting and Rebalancing", path: "40_PORTFOLIO_METHODS/QM007_PORTFOLIO_BACKTESTING_REBALANCING/article.html", folder: "QM007_PORTFOLIO_BACKTESTING_REBALANCING" },
      { id: "QM008", title: "Drawdown, Underwater Duration, and Recovery", path: "40_PORTFOLIO_METHODS/QM008_DRAWDOWN_UNDERWATER_DURATION_RECOVERY/article.html", folder: "QM008_DRAWDOWN_UNDERWATER_DURATION_RECOVERY" },
    ];

    const init = () => {
      const currentPath = decodeURIComponent(window.location.pathname);
      const current = methods.find((method) =>
        currentPath.includes(`/${method.folder}/`)
      );
      if (!current) return;

      const panel = document.createElement("nav");
      panel.className = "sq-method-browser";
      panel.setAttribute("aria-label", "Browse Quantitative Methods");

      const label = document.createElement("label");
      label.className = "sq-method-browser-label";
      label.htmlFor = "sq-method-browser-select";
      label.textContent = "Browse Methods";

      const controls = document.createElement("div");
      controls.className = "sq-method-browser-controls";

      const select = document.createElement("select");
      select.id = "sq-method-browser-select";
      select.className = "sq-method-browser-select";
      select.setAttribute("aria-label", "Choose another Quantitative Method");

      methods.forEach((method) => {
        const option = document.createElement("option");
        option.value = method.path;
        option.textContent = `${method.id} — ${method.title}`;
        option.selected = method.id === current.id;
        select.appendChild(option);
      });

      const methodMarker = "/methods/";
      let base = "/";
      const methodsIndex = currentPath.indexOf(methodMarker);
      if (methodsIndex >= 0) {
        base = currentPath.slice(0, methodsIndex + methodMarker.length);
      } else {
        const domainMarkers = [
          "/10_FORECAST_EVALUATION/",
          "/20_STATISTICAL_INFERENCE/",
          "/40_PORTFOLIO_METHODS/",
          "/80_DATA_RESEARCH_DESIGN/",
        ];
        for (const marker of domainMarkers) {
          const index = currentPath.indexOf(marker);
          if (index >= 0) {
            base = currentPath.slice(0, index + 1);
            break;
          }
        }
      }

      const resolve = (relativePath) => `${base}${relativePath}`;

      select.addEventListener("change", () => {
        window.location.assign(resolve(select.value));
      });

      const indexLink = document.createElement("a");
      indexLink.className = "sq-method-browser-index";
      indexLink.href = resolve("index.html");
      indexLink.target = "_self";
      indexLink.textContent = "All Methods";

      controls.appendChild(select);
      controls.appendChild(indexLink);
      panel.appendChild(label);
      panel.appendChild(controls);

      const kicker = document.querySelector(".method-kicker");
      const titleBlock = document.getElementById("title-block-header");
      const main = document.getElementById("quarto-document-content");
      if (kicker) {
        kicker.insertAdjacentElement("afterend", panel);
      } else if (titleBlock) {
        titleBlock.insertAdjacentElement("afterend", panel);
      } else if (main) {
        main.prepend(panel);
      }
    };

    if (document.readyState === "loading") {
      document.addEventListener("DOMContentLoaded", init, { once: true });
    } else {
      init();
    }
  })();
</script>
<script id="sq-external-link-policy">
  (() => {
    const canonicalHost = "research.slackquant.com";
    const apply = () => {
      document.querySelectorAll("a[href]").forEach((anchor) => {
        const href = anchor.getAttribute("href");
        if (!href) return;
        let url;
        try { url = new URL(href, window.location.href); } catch { return; }
        if (url.protocol !== "http:" && url.protocol !== "https:") return;
        const isFirstParty =
          url.origin === window.location.origin ||
          url.hostname === canonicalHost;
        const rel = new Set((anchor.rel || "").split(/\s+/).filter(Boolean));
        if (isFirstParty) {
          anchor.removeAttribute("target");
          rel.delete("noopener");
          rel.delete("noreferrer");
          if (rel.size) {
            anchor.rel = Array.from(rel).join(" ");
          } else {
            anchor.removeAttribute("rel");
          }
          return;
        }
        anchor.target = "_blank";
        rel.add("noopener");
        rel.add("noreferrer");
        anchor.rel = Array.from(rel).join(" ");
      });
    };
    if (document.readyState === "loading") {
      document.addEventListener("DOMContentLoaded", apply, { once: true });
    } else {
      apply();
    }
    new MutationObserver(apply).observe(document.documentElement, { childList: true, subtree: true });
  })();
</script>




<script src="../../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>